// 24 handcrafted Arrows levels — every level verified solvable.
// Mechanic: tap an arrow → it slides in its direction until it exits.
// Walls and other arrows block the slide. Player finds a valid order.

import type { Arrow, Level } from './types';

let _id = 0;
const aid = () => `a${++_id}`;

const arrow = (row: number, col: number, direction: Arrow['direction']): Arrow => ({ id: aid(), row, col, direction });

export const LEVELS: Level[] = [
  {
    id: 1,
    slug: 'first-step',
    title: 'First Step',
    rows: 3,
    cols: 3,
    arrows: [arrow(1, 0, 'left')],
    walls: [],
    hintsAllowed: 1,
    subtitle: 'Tap the arrow. Watch it glide out.',
    tier: 'intro',
    teach: 'Tap an arrow to slide it in its pointing direction. Reach the edge to extract it.',
  },
  {
    id: 2,
    slug: 'two-paths',
    title: 'Two Paths',
    rows: 3,
    cols: 4,
    arrows: [arrow(0, 0, 'right'), arrow(2, 0, 'down')],
    walls: [],
    hintsAllowed: 1,
    subtitle: 'Parallel arrows. Order is yours.',
    tier: 'intro',
  },
  {
    id: 3,
    slug: 'cross-currents',
    title: 'Cross Currents',
    rows: 3,
    cols: 4,
    arrows: [arrow(0, 0, 'up'), arrow(2, 3, 'down')],
    walls: [],
    hintsAllowed: 1,
    subtitle: 'Opposite directions, separate lanes.',
    tier: 'intro',
  },
  {
    id: 4,
    slug: 'one-blocks-one',
    title: 'One Blocks One',
    rows: 4,
    cols: 4,
    arrows: [arrow(0, 0, 'down'), arrow(0, 3, 'down')],
    walls: [],
    hintsAllowed: 1,
    subtitle: 'A sits in B’s lane. Move B first.',
    tier: 'intro',
    teach: 'If arrow A is in arrow B’s path, extract B first — or B will collide with A.',
  },
  {
    id: 5,
    slug: 'four-corners',
    title: 'Four Corners',
    rows: 5,
    cols: 5,
    arrows: [arrow(4, 0, 'down'), arrow(0, 0, 'down'), arrow(4, 4, 'left'), arrow(0, 4, 'down')],
    walls: [],
    hintsAllowed: 2,
    subtitle: 'Break the cycle — find the open corner.',
    tier: 'intro',
  },
  {
    id: 6,
    slug: 'the-chain',
    title: 'The Chain',
    rows: 5,
    cols: 4,
    arrows: [arrow(0, 2, 'up'), arrow(0, 1, 'down'), arrow(0, 0, 'down'), arrow(0, 3, 'left')],
    walls: [],
    hintsAllowed: 2,
    subtitle: 'A simple cascade.',
    tier: 'intro',
  },
  {
    id: 7,
    slug: 'first-wall',
    title: 'First Wall',
    rows: 5,
    cols: 5,
    arrows: [arrow(4, 0, 'down'), arrow(4, 4, 'left'), arrow(0, 0, 'down'), arrow(0, 4, 'down')],
    walls: [{ row: 2, col: 2 }],
    hintsAllowed: 2,
    subtitle: 'A wall reshapes the path.',
    tier: 'core',
    teach: 'Black walls block arrows. Plan extraction around them.',
  },
  {
    id: 8,
    slug: 'lattice',
    title: 'Lattice',
    rows: 5,
    cols: 5,
    arrows: [arrow(2, 4, 'down'), arrow(4, 2, 'left'), arrow(2, 0, 'down'), arrow(0, 2, 'right')],
    walls: [{ row: 2, col: 2 }],
    hintsAllowed: 2,
    subtitle: 'A single wall at the centre.',
    tier: 'core',
  },
  {
    id: 9,
    slug: 'twin-lanes',
    title: 'Twin Lanes',
    rows: 5,
    cols: 5,
    arrows: [arrow(4, 4, 'down'), arrow(0, 0, 'up'), arrow(4, 0, 'down'), arrow(0, 4, 'left')],
    walls: [],
    hintsAllowed: 2,
    subtitle: 'Lanes intersect — order matters.',
    tier: 'core',
  },
  {
    id: 10,
    slug: 'cornered',
    title: 'Cornered',
    rows: 4,
    cols: 4,
    arrows: [arrow(0, 1, 'right'), arrow(1, 3, 'down'), arrow(2, 0, 'down'), arrow(3, 2, 'up')],
    walls: [],
    hintsAllowed: 2,
    subtitle: 'Each arrow blocks another.',
    tier: 'core',
  },
  {
    id: 11,
    slug: 'inner-square',
    title: 'Inner Square',
    rows: 5,
    cols: 5,
    arrows: [arrow(3, 3, 'right'), arrow(1, 3, 'down'), arrow(1, 1, 'right'), arrow(3, 1, 'up')],
    walls: [],
    hintsAllowed: 2,
    subtitle: 'A square that turns inward.',
    tier: 'core',
  },
  {
    id: 12,
    slug: 'gatekeeper',
    title: 'Gatekeeper',
    rows: 5,
    cols: 5,
    arrows: [arrow(0, 4, 'right'), arrow(4, 4, 'right'), arrow(2, 2, 'right'), arrow(4, 0, 'left'), arrow(0, 0, 'right')],
    walls: [{ row: 1, col: 2 }, { row: 3, col: 2 }],
    hintsAllowed: 2,
    subtitle: 'The centre must rise before the sides.',
    tier: 'core',
  },
  {
    id: 13,
    slug: 'three-deep',
    title: 'Three Deep',
    rows: 5,
    cols: 5,
    arrows: [arrow(0, 4, 'right'), arrow(2, 1, 'up'), arrow(4, 4, 'right'), arrow(4, 0, 'right'), arrow(2, 3, 'right'), arrow(0, 0, 'down')],
    walls: [],
    hintsAllowed: 2,
    subtitle: 'Six arrows, one calm order.',
    tier: 'core',
  },
  {
    id: 14,
    slug: 'windmill',
    title: 'Windmill',
    rows: 5,
    cols: 5,
    arrows: [arrow(0, 2, 'left'), arrow(4, 2, 'down'), arrow(2, 0, 'down'), arrow(2, 4, 'down')],
    walls: [{ row: 2, col: 2 }],
    hintsAllowed: 2,
    subtitle: 'The wall at centre turns the wheel.',
    tier: 'core',
  },
  {
    id: 15,
    slug: 'crosshatch',
    title: 'Crosshatch',
    rows: 6,
    cols: 6,
    arrows: [arrow(5, 0, 'down'), arrow(5, 5, 'right'), arrow(2, 2, 'left'), arrow(3, 3, 'up'), arrow(0, 0, 'down'), arrow(0, 5, 'right')],
    walls: [{ row: 2, col: 4 }, { row: 3, col: 1 }],
    hintsAllowed: 2,
    subtitle: 'Layers within layers.',
    tier: 'advanced',
  },
  {
    id: 16,
    slug: 'cul-de-sac',
    title: 'Cul-de-sac',
    rows: 5,
    cols: 5,
    arrows: [arrow(0, 4, 'right'), arrow(0, 0, 'right'), arrow(4, 0, 'up'), arrow(4, 4, 'up'), arrow(1, 1, 'left'), arrow(3, 3, 'right')],
    walls: [{ row: 1, col: 3 }, { row: 3, col: 1 }],
    hintsAllowed: 2,
    subtitle: 'Walls create pockets — find what frees them.',
    tier: 'advanced',
  },
  {
    id: 17,
    slug: 'mirror',
    title: 'Mirror',
    rows: 6,
    cols: 6,
    arrows: [arrow(0, 5, 'up'), arrow(5, 0, 'left'), arrow(0, 0, 'down'), arrow(5, 5, 'up'), arrow(2, 2, 'right'), arrow(3, 3, 'left')],
    walls: [{ row: 1, col: 2 }, { row: 1, col: 3 }, { row: 4, col: 2 }, { row: 4, col: 3 }],
    hintsAllowed: 3,
    subtitle: 'A symmetry that deceives.',
    tier: 'advanced',
  },
  {
    id: 18,
    slug: 'long-shot',
    title: 'Long Shot',
    rows: 6,
    cols: 6,
    arrows: [arrow(0, 5, 'right'), arrow(0, 0, 'right'), arrow(5, 0, 'down'), arrow(2, 0, 'down'), arrow(5, 5, 'left'), arrow(3, 5, 'down')],
    walls: [{ row: 2, col: 3 }, { row: 3, col: 2 }],
    hintsAllowed: 3,
    subtitle: 'Long lanes reward patient order.',
    tier: 'advanced',
  },
  {
    id: 19,
    slug: 'spokes',
    title: 'Spokes',
    rows: 7,
    cols: 7,
    arrows: [arrow(5, 1, 'down'), arrow(6, 3, 'left'), arrow(3, 0, 'up'), arrow(1, 1, 'left'), arrow(5, 5, 'left'), arrow(1, 5, 'down'), arrow(0, 3, 'right'), arrow(3, 6, 'up')],
    walls: [{ row: 3, col: 3 }],
    hintsAllowed: 3,
    subtitle: 'Eight arrows radiating from a still centre.',
    tier: 'advanced',
  },
  {
    id: 20,
    slug: 'the-weave',
    title: 'The Weave',
    rows: 6,
    cols: 6,
    arrows: [arrow(0, 0, 'left'), arrow(0, 2, 'up'), arrow(0, 4, 'down'), arrow(5, 5, 'up'), arrow(5, 3, 'right'), arrow(5, 1, 'up')],
    walls: [{ row: 2, col: 2 }, { row: 3, col: 3 }],
    hintsAllowed: 3,
    subtitle: 'Threads cross. Untangle them.',
    tier: 'advanced',
  },
  {
    id: 21,
    slug: 'floodgate',
    title: 'Floodgate',
    rows: 7,
    cols: 7,
    arrows: [arrow(2, 4, 'up'), arrow(4, 4, 'right'), arrow(4, 2, 'down'), arrow(6, 0, 'down'), arrow(2, 2, 'left'), arrow(6, 6, 'down'), arrow(0, 0, 'down'), arrow(0, 6, 'down')],
    walls: [{ row: 3, col: 3 }, { row: 1, col: 3 }, { row: 5, col: 3 }],
    hintsAllowed: 3,
    subtitle: 'Open the gate in the right sequence.',
    tier: 'expert',
  },
  {
    id: 22,
    slug: 'two-islands',
    title: 'Two Islands',
    rows: 7,
    cols: 7,
    arrows: [arrow(3, 3, 'right'), arrow(0, 1, 'up'), arrow(0, 5, 'left'), arrow(6, 1, 'up'), arrow(6, 5, 'up'), arrow(3, 0, 'up')],
    walls: [{ row: 1, col: 3 }, { row: 5, col: 3 }],
    hintsAllowed: 3,
    subtitle: 'Two chambers, one logic.',
    tier: 'expert',
  },
  {
    id: 23,
    slug: 'concert',
    title: 'Concert',
    rows: 7,
    cols: 7,
    arrows: [arrow(0, 6, 'up'), arrow(6, 3, 'down'), arrow(3, 6, 'up'), arrow(6, 0, 'down'), arrow(0, 0, 'left'), arrow(3, 0, 'up'), arrow(0, 3, 'up'), arrow(6, 6, 'left')],
    walls: [{ row: 3, col: 3 }],
    hintsAllowed: 3,
    subtitle: 'Eight voices, one resolution.',
    tier: 'expert',
  },
  {
    id: 24,
    slug: 'final-bow',
    title: 'Final Bow',
    rows: 8,
    cols: 8,
    arrows: [arrow(2, 2, 'up'), arrow(4, 3, 'left'), arrow(7, 0, 'down'), arrow(7, 7, 'left'), arrow(5, 2, 'left'), arrow(5, 5, 'right'), arrow(3, 4, 'up'), arrow(2, 5, 'down'), arrow(0, 0, 'down'), arrow(0, 7, 'right')],
    walls: [{ row: 3, col: 3 }, { row: 4, col: 4 }],
    hintsAllowed: 3,
    subtitle: 'The closing movement.',
    tier: 'expert',
  },
];

export const getLevelBySlug = (slug: string) => LEVELS.find((l) => l.slug === slug);
export const getLevelById = (id: number) => LEVELS.find((l) => l.id === id);
